# # # # # # # #
#   VigneshJayavel   #
# # # # # # # #

# Basic
name:               "Vignesh Jayavel"
description:        "Rantings, "

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "//127.0.0.1:4000"
author:             "gfjaru"
twitter:
  username:         "gfjaru"
#facebook:
#  app_id:           1234
#    publisher:      1234

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "About"
    href:           "/about"
  - name:           "Books"
    href:           "/books"
  - name:           "Movies"
    href:           "/movies"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag
  - jekyll-gist